### ISSUE TITLE
Wrong asset url with laravel multiple locales

### ISSUE THREAD

**Issue by Mdpproduction** [Marwelln/laravel-multiple-locales#2]
Hi,
i'm just trying to use this package, and i see these errors with chrome:

GET http://localhost:8000/en/assets/stylesheets 
en:319 GET http://localhost:8000/en/assets/javascript 
en:322 Uncaught ReferenceError: PhpDebugBar is not defined(anonymous function) @ en:322

And that mechanism collides with my admin routes.

It seems that something goes wrong with debugbar package for laravel.
any suggestions ?

**Comment by Marwelln** [comment]
Use https://laracasts.com/discuss if you need help. I don't work with web development anymore.
